# Generated by Django 4.2.4 on 2023-08-13 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('primer_apellido', models.CharField(max_length=25, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, verbose_name='Segundo Apellido')),
                ('numero_ide', models.CharField(max_length=15, verbose_name='Numero Identificación')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('nit', models.IntegerField(blank=True, verbose_name='Nit')),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Estado_Habitacion',
            fields=[
                ('id_estado_habitacion', models.AutoField(primary_key=True, serialize=False, verbose_name='id estado habitacion')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Estado_Habitacion',
            },
        ),
        migrations.CreateModel(
            name='Estado_Reserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Reserva')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Estado_Reserva',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Factura')),
                ('fecha_hora', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Hora')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto Total')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Habitacion')),
                ('nro', models.IntegerField(verbose_name='Numero Habitacion')),
                ('ubicacionpiso', models.IntegerField(verbose_name='Piso/Planta')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de Habitacion')),
                ('nro_camas', models.IntegerField(verbose_name='Numero de camas')),
                ('precio_noche', models.DecimalField(decimal_places=2, default='100', max_digits=5, verbose_name='Precio Noche')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Detalle/Observacion')),
                ('id_estado_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.estado_habitacion')),
            ],
            options={
                'verbose_name_plural': 'Habitacion',
            },
        ),
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_metodo_pago')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion Metodo Pago')),
            ],
            options={
                'verbose_name_plural': 'Metodo_Pago',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Factura')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha Salida')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo total')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.cliente', verbose_name='Cliente')),
                ('id_estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.estado_reserva', verbose_name='Estado Reserva')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.habitacion', verbose_name='Habitacion')),
            ],
            options={
                'verbose_name_plural': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Factura_Detalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.factura', verbose_name='Factura')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
