# Generated by Django 4.2.4 on 2023-08-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factura_Detalla',
            new_name='Factura_Detalle',
        ),
    ]
