# Generated by Django 4.2.4 on 2023-08-14 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_factura_detalla_factura_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_editar',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Hora'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Hora'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Hora'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id_estado_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.estado_habitacion', verbose_name='id estado habitacion'),
        ),
    ]
